// Data for the cards
const cardData = [
    {
        logo: "assets/logos/com_logo_1.png",
        title: "Nova Agritech Ltd.",
        priceBand: "Rs 39 - 41",
        openDate: "2024-01-22",
        closeDate: "2024-01-24",
        issueSize: "143.81 Cr.",
        issueType: "Book Built",
        listingDate: "2024-01-30",
        rhp : "assets/rhp/sample_rhp.pdf",
        drhp : "assets/drhp/sample_drhp.pdf"
    },
    {
        logo: "assets/logos/com_logo_2.png",
        title: "EPACK Durable Ltd.",
        priceBand: "Rs 218 - 230",
        openDate: "2024-01-19",
        closeDate: "2024-01-23",
        issueSize: "640.05 Cr.",
        issueType: "Book Built",
        listingDate: "2024-01-28",
        rhp : "assets/rhp/sample_rhp.pdf",
        drhp : "assets/drhp/sample_drhp.pdf"
    },
    {
        logo: "assets/logos/com_logo_3.png",
        title: "RK Swamy Ltd.",
        priceBand: "Not Issued",
        openDate: "Not Issued",
        closeDate: "Not Issued",
        issueSize: "Not Issued",
        issueType: "Book Built",
        listingDate: "Not Issued",
        rhp : "assets/rhp/sample_rhp.pdf",
        drhp : "assets/drhp/sample_drhp.pdf"
    },
    {
        logo: "assets/logos/com_logo_4.png",
        title: "Oravel Stays Ltd.",
        priceBand: "Not Issued",
        openDate: "Not Issued",
        closeDate: "Not Issued",
        issueSize: "8430 Cr.",
        issueType: "Book Built",
        listingDate: "Not Issued",
        rhp : "assets/rhp/sample_rhp.pdf",
        drhp : "assets/drhp/sample_drhp.pdf"
    },
    {
        logo: "assets/logos/com_logo_5.png",
        title: "Imagine marketing Ltd.",
        priceBand: "Not Issued",
        openDate: "Not Issued",
        closeDate: "Not Issued",
        issueSize: "2000 Cr.",
        issueType: "Book Built",
        listingDate: "Not Issued",
        rhp : "assets/rhp/sample_rhp.pdf",
        drhp : "assets/drhp/sample_drhp.pdf"
    },
    {
        logo: "assets/logos/com_logo_6.png",
        title: "Kids Clinic India Ltd.",
        priceBand: "Not Issued",
        openDate: "Not Issued",
        closeDate: "Not Issued",
        issueSize: "Not Issued",
        issueType: "Book Built",
        listingDate: "Not Issued",
        rhp : "assets/rhp/sample_rhp.pdf",
        drhp : "assets/drhp/sample_drhp.pdf"
    },
    {
        logo: "assets/logos/com_logo_7.png",
        title: "OLA Electric Mobility Ltd.",
        priceBand: "Not Issued",
        openDate: "Not Issued",
        closeDate: "Not Issued",
        issueSize: "Not Issued",
        issueType: "Book Built",
        listingDate: "Not Issued",
        rhp : "assets/rhp/sample_rhp.pdf",
        drhp : "assets/drhp/sample_drhp.pdf"
    },
    {
        logo: "assets/logos/com_logo_8.png",
        title: "One Mobikwik Systems Ltd.",
        priceBand: "Not Issued",
        openDate: "Not Issued",
        closeDate: "Not Issued",
        issueSize: "1800 Cr.",
        issueType: "Book Built",
        listingDate: "Not Issued",
        rhp : "assets/rhp/sample_rhp.pdf",
        drhp : "assets/drhp/sample_drhp.pdf"
    },
    {
        logo: "assets/logos/com_logo_9.png",
        title: "Le Travenues Technology",
        priceBand: "Not Issued",
        openDate: "Not Issued",
        closeDate: "Not Issued",
        issueSize: "1600 Cr.",
        issueType: "Book Built",
        listingDate: "Not Issued",
        rhp : "assets/rhp/sample_rhp.pdf",
        drhp : "assets/drhp/sample_drhp.pdf"
    },
    {
        logo: "assets/logos/com_logo_10.png",
        title: "CMR Green Technologies",
        priceBand: "Not Issued",
        openDate: "Not Issued",
        closeDate: "Not Issued",
        issueSize: "Not Issued",
        issueType: "Book Built",
        listingDate: "Not Issued",
        rhp : "assets/rhp/sample_rhp.pdf",
        drhp : "assets/drhp/sample_drhp.pdf"
    },
    {
        logo: "assets/logos/com_logo_11.png",
        title: "Wellness Forever",
        priceBand: "Not Issued",
        openDate: "Not Issued",
        closeDate: "Not Issued",
        issueSize: "Not Issued",
        issueType: "Book Built",
        listingDate: "Not Issued",
        rhp : "assets/rhp/sample_rhp.pdf",
        drhp : "assets/drhp/sample_drhp.pdf"
    },
    {
        logo: "assets/logos/com_logo_12.png",
        title: "PKH Ventures Ltd.",
        priceBand: "Not Issued",
        openDate: "Not Issued",
        closeDate: "Not Issued",
        issueSize: "Not Issued",
        issueType: "Book Built",
        listingDate: "Not Issued",
        rhp : "assets/rhp/sample_rhp.pdf",
        drhp : "assets/drhp/sample_drhp.pdf"
    }
];